extraObjects:
  envoyGatewayClass:
    apiVersion: gateway.networking.k8s.io/v1
    kind: GatewayClass
    metadata:
      name: envoy-internal
    spec:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
  internalGatewayCert:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: internal-wildcard-tls
      annotations:
        cert-manager.io/issuer: letsencrypt
    spec:
      commonName: "*.{{ .Values.domain }}"
      dnsNames:
        - "*.{{ .Values.domain }}"
      secretName: internal-wildcard-tls
  internalGateway:
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: internal
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    spec:
      gatewayClassName: envoy-internal
      listeners:
        - name: http
          protocol: HTTP
          port: 80
          allowedRoutes:
            namespaces:
              from: All
        - name: https
          protocol: HTTPS
          hostname: "*.{{ .Values.domain }}"
          port: 443
          tls:
            mode: Terminate
            certificateRefs:
              - name: internal-wildcard-tls
                kind: Secret
          allowedRoutes:
            namespaces:
              from: All
