extraObjects:
  exposedGatewayClass:
    apiVersion: gateway.networking.k8s.io/v1
    kind: GatewayClass
    metadata:
      name: envoy-exposed
    spec:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
  exposedGatewayCert:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: exposed-wildcard-tls
      annotations:
        cert-manager.io/issuer: letsencrypt
    spec:
      commonName: "*.{{ .Values.domain }}"
      dnsNames:
        - "*.{{ .Values.domain }}"
      secretName: exposed-wildcard-tls
      issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
  exposedGateway:
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: exposed
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    spec:
      gatewayClassName: envoy-exposed
      allowedListeners:
        namespaces:
          from: All
      listeners:
        - name: http
          protocol: HTTP
          port: 80
          allowedRoutes:
            namespaces:
              from: All
        - name: https
          protocol: HTTPS
          hostname: "*.{{ .Values.domain }}"
          port: 443
          tls:
            mode: Terminate
            certificateRefs:
              - group: ''	
                name: internal-wildcard-tls
                kind: Secret
          allowedRoutes:
            namespaces:
              from: All
