extraObjects:
  publicGatewayClass:
    apiVersion: gateway.networking.k8s.io/v1
    kind: GatewayClass
    metadata:
      name: public
    spec:
      controllerName: "{{ .domain }}/public"
  publicGateway:
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: public
      namespace: envoy-gateway-system
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    spec:
      gatewayClassName: public
      listeners:
        - name: http
          protocol: HTTP
          port: 80
          allowedRoutes:
            namespaces:
              from: All
        - name: https
          protocol: HTTPS
          hostname: "*.{{ .domain }}"
          port: 443
          tls:
            mode: Terminate
            certificateRefs:
              - name: public-tls
                kind: Secret
          allowedRoutes:
            namespaces:
              from: All
