---
internal_ingress_namespace: "ingress-internal"
internal_ingress_tailscale_chart_version: "1.90.6"
internal_ingress_nginx_chart_version: "4.14.0"

# Deployment managed by Argo
external_ingress_namespace: "ingress-external"
